name: Deploy Frontend

on:
  push:
    branches: [ main, dev ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set environment variables
        id: vars
        run: |
          echo "Current branch: ${{ github.ref }}"
          
          if [[ ${{ github.ref }} == 'refs/heads/main' ]]; then
            echo "::set-output name=env_name::prod"
            echo "::set-output name=compose_file::docker-compose.prod.yml"
            echo "::set-output name=port::8082"
            echo "::set-output name=environment::production"
            echo "::set-output name=base_url::${{ vars.PROD_BASE_URL }}"
            echo "::set-output name=api_url::${{ vars.PROD_BASE_API_URL }}"
            echo "::set-output name=google_client_id::${{ vars.PROD_GOOGLE_CLIENT_ID }}"
            echo "::set-output name=google_analytics_measurement_id::${{ vars.PROD_GOOGLE_ANALYTICS_MEASUREMENT_ID }}"
            echo "::set-output name=clarity_id::${{ vars.PROD_CLARITY_ID }}"
          else
            echo "::set-output name=env_name::dev"
            echo "::set-output name=compose_file::docker-compose.dev.yml"
            echo "::set-output name=port::8081"
            echo "::set-output name=environment::development"
            echo "::set-output name=base_url::${{ vars.DEV_BASE_URL }}"
            echo "::set-output name=api_url::${{ vars.DEV_BASE_API_URL }}"
            echo "::set-output name=google_client_id::${{ vars.DEV_GOOGLE_CLIENT_ID }}"
            echo "::set-output name=clarity_id::${{ vars.DEV_CLARITY_ID }}"
          fi
          
          echo "Environment name: ${{ steps.vars.outputs.env_name }}"

      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Exit on any error
            set -e
            
            echo "Environment name: ${{ steps.vars.outputs.env_name }}"
            
            # Navigate to appropriate directory
            cd /home/apps/drawberry/drawberry-frontend/${{ steps.vars.outputs.env_name }}
            
            pwd
            
            # Pull latest changes
            git pull origin ${{ github.ref_name }}
            
            # Create environment file
            cat > .env << EOF
            PORT=${{ steps.vars.outputs.port }}
            VUE_APP_ENVIRONMENT=${{ steps.vars.outputs.environment }}
            VUE_APP_BASE_URL=${{ steps.vars.outputs.base_url }}
            VUE_APP_BASE_API_URL=${{ steps.vars.outputs.api_url }}
            VUE_APP_GOOGLE_CLIENT_ID=${{ steps.vars.outputs.google_client_id }}
            VUE_APP_SENTRY_DSN=${{ vars.VUE_APP_SENTRY_DSN }}
            SENTRY_AUTH_TOKEN=${{ secrets.SENTRY_AUTH_TOKEN }}
            VUE_APP_GOOGLE_ANALYTICS_MEASUREMENT_ID=${{ steps.vars.outputs.google_analytics_measurement_id }}
            VUE_APP_CLARITY_ID=${{ steps.vars.outputs.clarity_id }}
            EOF
            
            echo "Build and restart using appropriate compose file.."
            docker-compose -f docker-compose.yml -f ${{ steps.vars.outputs.compose_file }} up -d --build
            
            echo "Clean up old images..."
            docker image prune -f
            
            echo "Deployment completed successfully!"