name: CI

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deployment:
    runs-on: self-hosted
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '21.x'

      - name: List files
        run: ls

      - name: Install dependencies
        run: yarn install

      - name: 'Create env file'
        run: |
          touch .env
          echo VUE_APP_ENVIRONMENT="development" >> .env
          echo VUE_APP_BASE_URL="https://dev.app.drawberry.io" >> .env
          echo  VUE_APP_BASE_API_URL="https://dev.api.drawberry.io" >> .env
          echo  VUE_APP_GOOGLE_CLIENT_ID="${{ secrets.VUE_APP_GOOGLE_CLIENT_ID }}" >> .env

          cat .env

      - name: Build
        run: |
          rm -rf dist
          node --version
#          yarn install
          npm run build
